#  Copyright (c) 2025,2026 by ESA Sen4CAP team and contributors
#  Permissions are hereby granted under the terms of the Apache 2.0 License:
#  https://opensource.org/license/apache-2-0.

site_name: ESA Sen4CAP Client
repo_url: https://github.com/Sen4CAP/sen4cap-client
repo_name: sen4cap-client

copyright: Copyright &copy; 2025-2026 ESA Sen4CAP Team

# Ignore copies left by older notebook-based builds.
exclude_docs: |
  /notebooks/

validation:
  links:
    not_found: warn
    unrecognized_links: warn
    anchors: warn

nav:
  - Overview: index.md
  - Installation: installation.md
  - Configuration: configuration.md
  - User Guides:
    - Python API: guides/api.md
    - App: guides/app.md
    - Command Line: guides/cli.md
  - API Reference: api.md
  - CLI Reference: cli.md
  - Request Format: request-format.md
  - Contributing: contributing.md

theme:
  name: material
  logo: assets/icon.png
  favicon: assets/favicon.ico
  palette:
    # Palette toggle for light mode
    - scheme: default
      primary: blue grey
      accent: deep orange
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      primary: blue grey
      accent: deep orange
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.top

markdown_extensions:
  - attr_list
  - admonition
  - pymdownx.details
  - pymdownx.highlight:
      pygments_lang_class: true
  - pymdownx.superfences
  - pymdownx.snippets:
      base_path: !relative $config_dir
      check_paths: true
      dedent_subsections: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Sen4CAP/sen4cap-client
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/sen4cap-client/

plugins:
  - search
  - autorefs
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: google
            show_root_toc_entry: true
            show_root_heading: true
            show_source: true
            heading_level: 2
            annotations_path: brief
            members_order: source

extra_css:
    - overrides/css/custom.css
